defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
    values:
      layout: "default" # overrides previous default layout
      author: "Project PANOPTES Team"
